/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/BasaltoOxidado.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-8.75, -3.83, -7.51]} rotation={[-3.11, 0.73, 0.28]} scale={[74.61, 74.61, 74.61]}>
        <mesh geometry={nodes.texturedMesh_1.geometry} material={materials['TextureAtlas_1001.002']} />
        <mesh geometry={nodes.texturedMesh_2.geometry} material={materials['TextureAtlas_1002.002']} />
        <mesh geometry={nodes.texturedMesh_3.geometry} material={materials.TextureAtlas_1003} />
        <mesh geometry={nodes.texturedMesh_4.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.texturedMesh_5.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.texturedMesh_6.geometry} material={materials['Material.005']} />
      </group>
    </group>
  )
}

useGLTF.preload('/BasaltoOxidado.glb')
