/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Danburita.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0.01, 0.72, 0.04]} rotation={[-1.59, 0.08, 2.43]} scale={[1.04, 1.04, 1.04]}>
        <mesh geometry={nodes.texturedMesh_1.geometry} material={materials.TextureAtlas_0} />
        <mesh geometry={nodes.texturedMesh_2.geometry} material={materials.TextureAtlas_1} />
        <mesh geometry={nodes.texturedMesh_3.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.texturedMesh_4.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.texturedMesh_5.geometry} material={materials['Material.005']} />
      </group>
    </group>
  )
}

useGLTF.preload('/Danburita.glb')
