/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Magnetita.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0.33, 2.18, -0.18]} rotation={[-1.95, 0, 0]} scale={5.42}>
        <mesh geometry={nodes.texturedMesh001_1.geometry} material={materials['TextureAtlas_0.001']} />
        <mesh geometry={nodes.texturedMesh001_2.geometry} material={materials['TextureAtlas_1.001']} />
        <mesh geometry={nodes.texturedMesh001_3.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.texturedMesh001_4.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.texturedMesh001_5.geometry} material={materials['Material.005']} />
      </group>
    </group>
  )
}

useGLTF.preload('/Magnetita.glb')
