/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Wulfenita.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-0.37, 1.98, -0.24]} rotation={[-2.12, -0.59, 0.75]} scale={[6.99, 6.99, 6.99]}>
        <mesh geometry={nodes.texturedMesh001_1.geometry} material={materials['TextureAtlas_0.001']} />
        <mesh geometry={nodes.texturedMesh001_2.geometry} material={materials['TextureAtlas_1.001']} />
        <mesh geometry={nodes.texturedMesh001_3.geometry} material={materials['TextureAtlas_2.001']} />
        <mesh geometry={nodes.texturedMesh001_4.geometry} material={materials['TextureAtlas_3.001']} />
        <mesh geometry={nodes.texturedMesh001_5.geometry} material={materials.Material} />
        <mesh geometry={nodes.texturedMesh001_6.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.texturedMesh001_7.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.texturedMesh001_8.geometry} material={materials['Material.005']} />
      </group>
    </group>
  )
}

useGLTF.preload('/Wulfenita.glb')
